#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Generate and upload code coverage reports.
#
# This *must* be run from inside an existing build after compiling with
# appropriate coverage flags and running tests.
#-----------------------------------------------------------------------------#

name: "Generate and upload coverage report"
description: "Generates coverage report using gcovr and uploads to Codecov"
inputs:
  token:
    description: "Codecov token"
    required: true
  working-directory:
    description: "Working directory for coverage generation"
    required: false
    default: "."
  name:
    description: "Name for the codecov upload"
    required: true
  gcov-exe:
    description: "Path to gcov executable (if using llvm, set to llvm-gcov)"
    required: false
    default: "gcov"
  gcovr-config-path:
    description: "Path to gcovr config file"
    required: false
    default: "${{github.workspace}}/scripts/ci/gcovr.cfg"

runs:
  using: "composite"
  steps:
    - name: Generate coverage report
      shell: sh
      working-directory: ${{inputs.working-directory}}
      run: |
        gcovr \
          --config=${{inputs.gcovr-config-path}} \
          --gcov-executable=${{inputs.gcov-exe}} \
          -j $(($(nproc) + 1)) \
          --output=cobertura-cov.xml --cobertura-pretty \
          --merge-mode-functions=merge-use-line-min

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7.0.0 # immutable, 6 June 2026
      with:
        token: ${{inputs.token }}
        fail_ci_if_error: ${{inputs.fail_ci_if_error}}
        name: ${{inputs.name}}
        files: ${{inputs.working-directory}}/cobertura-cov.xml
        verbose: true
        gcov-exe: ${{inputs.gcov-exe}}
