#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build using CUDA/ROCm docker images
#-----------------------------------------------------------------------------#

name: build-docker
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

concurrency:
  group: build-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  # TODO: since we don't build on GPU systems with cuda/rocm docker,
  # none of the tests actually run on device
  gpu:
    name: >-
      ${{format('{0}{1}{2}-{3}-{4}',
                matrix.special,
                matrix.special && '-' || '',
                matrix.geometry,
                matrix.buildtype,
                matrix.image)}}
    strategy:
      fail-fast: false
      matrix:
        special: [null]
        geometry: ["orange"]
        buildtype: ["ndebug"]
        image: ["7:2025-11-04", "7:2025-11-01", "6:2025-01-02"]

    env:
      CELER_TEST_STRICT: 0 # TODO: enable with Geant4 v11.3
      CELER_DISABLE_DEVICE: 1 # REQUIRED for GHA runners
      CMAKE_PRESET: >-
        ${{format('{0}-{1}{2}{3}',
                matrix.buildtype,
                matrix.geometry,
                matrix.special && '-' || '',
                matrix.special)}}
    runs-on: ubuntu-24.04
    container:
      image: docker.io/celeritas/ci-ubuntu-rocm${{matrix.image}}
    steps:
      - name: Find all files
        run: |
          find /opt -type d

# vim: set nowrap tw=100:
