#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Deploy documentation after pushes to develop.
#-----------------------------------------------------------------------------#

name: deploy-pages
on:
  # Enable testing via workflow dispatch
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "Run ID from build-docs workflow to test"
        required: true
        type: number
  workflow_call: {}

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: deploy-pages-${{github.event_name}}-${{github.event_name == 'pull_request' && github.event.number || github.ref_name}}
  cancel-in-progress: false

jobs:
  update-pubs:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Celeritas doc base
        uses: actions/checkout@v7
        with:
          ref: doc/gh-pages-base
      - uses: actions/setup-python@v7
        with:
          python-version-file: .python-version
      - name: Install Python packages
        # NOTE: this is the requirements path in the orphaned
        # doc/gh-pages-base branch, NOT the Celeritas branch!
        run: |
          pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Update publications
        id: update
        env:
          ZOTERO_TOKEN: ${{secrets.ZOTERO_TOKEN}}
          ZOTERO_GROUP: 2380941
        run: |
          python scripts/generate-pubs.py -g $ZOTERO_GROUP
          echo "DIFF_COUNT=$(git diff -- publications.md | wc -l)" >> $GITHUB_OUTPUT
      - name: Push updated publications to doc branch
        if: >-
          ${{ steps.update.outcome != 'failure'
              && fromJSON(steps.update.outputs.DIFF_COUNT) > 0 }}
        continue-on-error: true
        run: |
          git commit \
            -c user.name="Github Action" \
            -c user.email="${{github.triggering_actor}}@users.noreply.github.com" \
            -am "Update publications"
          git push

  build-jekyll:
    runs-on: ubuntu-24.04
    needs: update-pubs
    env:
      CELER_UPLOAD_DIR: build-jekyll
      CELER_DOC_NAME: doc-jekyll
    steps:
      - name: Check out Celeritas doc base
        uses: actions/checkout@v7
        with:
          ref: doc/gh-pages-base
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          destination: jekyll-build
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{env.CELER_UPLOAD_DIR}}
          name: ${{env.CELER_DOC_NAME}}
          if-no-files-found: error
          overwrite: true
          retention-days: 1

  build-site:
    runs-on: ubuntu-24.04
    needs: update-pubs
    steps:
      - name: Check out Celeritas doc base
        uses: actions/checkout@v7
        with:
          ref: doc/gh-pages-base
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Download doc and user artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: "doc-*" # see build-docs.yml and build-jekyll
          run-id: ${{inputs.workflow_run_id || github.event.workflow_run.id}}
      - name: Rename artifacts
        run: |
          mv doc-dev dev
          mv doc-user user
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5

  deploy:
    runs-on: ubuntu-24.04
    needs: build-site
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

# vim: set nowrap tw=100:
